name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  REGION: us-central1
  AR_REPO: risklens
  SERVICE_NAME: risklens-api
  IMAGE_NAME: risklens-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - run: echo "Authenticating to Google Cloud..."
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - run: echo "Done."
      
      - run: echo "Setting up Google Cloud..."
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
      - run: echo "Done."
        
      - run: echo "Configuring Docker..."
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
      - run: echo "Done."

      - run: echo "Building Docker image..."
      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
      - run: echo "Done."

      - run: echo "Pushing image to Artifact registry..."
      - name: Push image to Artifact Registry
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      - run: echo "Done."
      
      - run: echo "Deploying to Cloud Run..."
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      - run: echo "Done."
  test:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install dotenv requests
      - name: Test endpoint
        run: python test_score.py
        env: 
          API_URL: ${{ secrets.API_URL }}